name: LazuliTeleport
author: Endermanbugzjfc
version: 1.0.0
api: 4.0.0
main: Endermanbugzjfc\LazuliTeleport\LazuliTeleport
src-namespace-prefix: Endermanbugzjfc\LazuliTeleport
website: https://github.com/Endermanbugzjfc/LazuliTeleport
depend:
  - InfoAPI
softdepend:
  - Capital

permissions:
  lazuliteleport.tpa:
    description: "Allow player to use /tpa"
    default: true
  lazuliteleport.tpaccept:
    description: "Allow player to use /tpaccept"
    default: true
  lazuliteleport.tpareject:
    description: "Allow player to use /tpareject"
    default: true
  lazuliteleport.tpahere:
    description: "Allow player to use /tpahere"
    default: true
  lazuliteleport.tpablock:
    description: "Allow player to use /tpablock"
    default: true