name: LazuliTeleport
author: Endermanbugzjfc
version: 1.0.0
api: 4.0.0
main: Endermanbugzjfc\LazuliTeleport\LazuliTeleport
src-namespace-prefix: Endermanbugzjfc\LazuliTeleport
website: https://github.com/Endermanbugzjfc/LazuliTeleport
depend:
  - InfoAPI
softdepend:
  - Capital

# I want the commands to be hidden by default.
# So I removed all defaults.
permissions:
  lazuliteleport.tpa:
    description: "Allow player to use /tpa"
  lazuliteleport.tpaccept:
    description: "Allow player to use /tpaccept"
  lazuliteleport.tpareject:
    description: "Allow player to use /tpareject"
  lazuliteleport.tpahere:
    description: "Allow player to use /tpahere"
  lazuliteleport.tpablock:
    description: "Allow player to use /tpablock"
